In [1]:
# Import the needed libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

In [ ]:
# - - Description of the dataset - -

# This dataset that we ended up choosing is the "IMBD: Data of the top 1000 movies
#  - scraped from the IMDB website. Dataset also duplicates a movie in another row if the movie consists
#  of more than one genre. Missing values present in 'gross(M)' and 'metascore' column represented as 0.00 and 0 respectively."

# We ended up going with the clean version, as it was easier to work with and had "less" missing values, but still present.
# The targeted value for this dataset is gross(M).

In [7]:
# Read the dataset
imbd_dataset = pd.read_csv('../Oblig 1/Dataset/imdb_clean.csv')
# Uses existing column names baked into csv file.

# Show the first 5 rows to validate that the data import has been successful
imbd_dataset.head()

,Unnamed: 0,title,director,release_year,runtime,genre,rating,metascore,gross(M)
0,0,The Shawshank Redemption,Frank Darabont,1994,142,Drama,9.3,82,28.34
1,1,The Godfather,Francis Ford Coppola,1972,175,Crime,9.2,100,134.97
2,1,The Godfather,Francis Ford Coppola,1972,175,Drama,9.2,100,134.97
3,2,The Dark Knight,Christopher Nolan,2008,152,Action,9.0,84,534.86
4,2,The Dark Knight,Christopher Nolan,2008,152,Crime,9.0,84,534.86

In [8]:
# Dropping unnecessary data. The Unnamed 0 is just an identifier and not needed for analysis
imbd_clean_dataset = imbd_dataset.drop('Unnamed: 0', axis=1)
imbd_clean_dataset.head()

,title,director,release_year,runtime,genre,rating,metascore,gross(M)
0,The Shawshank Redemption,Frank Darabont,1994,142,Drama,9.3,82,28.34
1,The Godfather,Francis Ford Coppola,1972,175,Crime,9.2,100,134.97
2,The Godfather,Francis Ford Coppola,1972,175,Drama,9.2,100,134.97
3,The Dark Knight,Christopher Nolan,2008,152,Action,9.0,84,534.86
4,The Dark Knight,Christopher Nolan,2008,152,Crime,9.0,84,534.86

In [10]:
# Look at the implementation details, data types and missing data
imbd_clean_dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 2532 entries, 0 to 2531
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         2532 non-null   str
 1   director      2532 non-null   str
 2   release_year  2532 non-null   int64
 3   runtime       2532 non-null   int64
 4   genre         2532 non-null   str
 5   rating        2532 non-null   float64
 6   metascore     2532 non-null   int64
 7   gross(M)      2532 non-null   float64
dtypes: float64(2), int64(3), str(3)
memory usage: 158.4 KB

In [9]:
# Count the number of missing values in the dataset
imbd_clean_dataset.isna().sum()

title           0
director        0
release_year    0
runtime         0
genre           0
rating          0
metascore       0
gross(M)        0
dtype: int64